name: Prepare Dependencies

description: Checkout code, set up Node.js, and install dependencies.

runs:
  using: composite
  steps:
    - name: Prepare Corepack
      run: corepack enable
      shell: bash

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: yarn
        cache-dependency-path: ./yarn.lock
        registry-url: https://registry.npmjs.org
        scope: '@altearius'

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
